### ISSUE TITLE
ANSIBLE_VAULT_PASSWORD_FILE does not work as expected

### ISSUE THREAD

**Issue by BOPOHA** [sadv1r/ansible-vault-editor-idea-plugin#122]
According to resolved issue https://github.com/sadv1r/ansible-vault-editor-idea-plugin/issues/90 and the PR #94
the plugin looks password in file as plaintext value.

But password can be also specified [as a script](https://docs.ansible.com/ansible/2.8/user_guide/playbooks_vault.html#running-a-playbook-with-vault):
```
ansible-playbook site.yml --vault-password-file ~/.your_vault_password_file
```

where `~/.your_vault_password_file` can be **executable** and looks like one of the examples:

```
#!/bin/sh
echo "vault_password_here"
```

```
#!/usr/bin/pass PASSWORD/STORE/ANSIBLE/VAULT/PATH
```

```
#!/bin/sh
aws ssm get-parameter --name ..... 
```

```
#!/bin/python
print("vault_password_here")
```

it would be good to add additional check the permissions of the file, 
and if it's executable, get the password from stdout.

**Comment by sadv1r** [comment]
Thanks for this info! Somehow missed this part of the doc and I think it will be a good feature to add
