### ISSUE TITLE
Plugin breaks with IntelliJ build IU-213.5744.223

### ISSUE THREAD

**Issue by zcubbs** [sadv1r/ansible-vault-editor-idea-plugin#124]
Plugin error: Plugin 'Ansible Vault Editor' (version '1.15') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is IU-213.5744.223

**Comment by sadv1r** [comment]
Hello @zcubbs! Thank you for reporting! This already bean fixed, but version will be approved within two days.
You can now manually install it from here: https://plugins.jetbrains.com/plugin/14278-ansible-vault-editor/versions/stable/148166

**Comment by zcubbs** [comment]
Thank you
