### ISSUE TITLE
Please support PyCharm 2021.3

### ISSUE THREAD

**Issue by ruurd** [sadv1r/ansible-vault-editor-idea-plugin#127]
Currently the plugin is unsupported in PyCharm 2021.3

Please make sure support is available for the new versions.

**Comment by sadv1r** [comment]
Hello @ruurd! Thank you for reporting! This already been fixed, but version will be approved within two days.
You can now manually install it from here: https://plugins.jetbrains.com/plugin/14278-ansible-vault-editor/versions/stable/148166

Additionally this problem will be fixed here #125

**Comment by ruurd** [comment]
That's good. Thank you Dmitry!
