### ISSUE TITLE
Password encrypt issues.

### ISSUE THREAD

**Issue by iangregsondev** [sadv1r/ansible-vault-editor-idea-plugin#132]
Hi,

I have the ENV variable set and it appears that decrypting an already encrypted file - works great.

BUT a new file and I choose to encrypt it and it always asks for the password.

If I enter the password and choose NOT TO SAVE it ...

then decrypt it after - it works.

Thanks.

**Comment by sadv1r** [comment]
Hi, thanks for feedback, I'll try to reproduce this

**Comment by mordekasg** [comment]
@sadv1r 
[In here](https://github.com/sadv1r/ansible-vault-editor-idea-plugin/blob/5bb4dea50f3f7a0f5a4b08c0cf55577eaaaffbf2/src/main/kotlin/ru/sadv1r/idea/plugin/ansible/vault/editor/Vault.kt#L64), there is only check for decryption of text/file one want to encrypt and in case of failure it just opens password popup.

Also [here](https://github.com/sadv1r/ansible-vault-editor-idea-plugin/blob/5bb4dea50f3f7a0f5a4b08c0cf55577eaaaffbf2/src/main/kotlin/ru/sadv1r/idea/plugin/ansible/vault/editor/action/FileEncryptAction.kt#L22), `FileEncryptAction` is not using `vault.openEditor()` method.

So, there should be some small logic for that process but its too late for me right now to think about it, maybe tomorrow :sweat_smile:.

**Comment by mordekasg** [comment]
Are you using Vault IDs to distinguish the difference between PROD and DEV passwords? Or you are just using password file from ENV as default (e.g. for DEV) and manually provide different password for PROD?

In ansible, if you export password file ENV (ANSIBLE_VAULT_PASSWORD_FILE), it is used as encryption/decryption password file.

So the easiest way to allow users like myself, use ENV as default encryption/decryption password file would be to add configuration checkbox: "Always use found ENV password file to encrypt/decrypt data".
It would be also useful to display there current value of ENV/password file used by plugin.

**Comment by sadv1r** [comment]
Didn't know that ANSIBLE_VAULT_PASSWORD_FILE is used for encryption too, thanks! So, we need it to work here the same way and I'll look into it.

And I like your idea about having a way to configure this differently and to see if a plugin can see an ENV or another configuration of a password file

**Comment by sadv1r** [comment]
Fixed in [v1.20](https://plugins.jetbrains.com/plugin/14278-ansible-vault-editor/versions/stable/268986)
