### ISSUE TITLE
ANSIBLE_VAULT_PASSWORD_FILE is ignored

### ISSUE THREAD

**Issue by RickS-C137** [sadv1r/ansible-vault-editor-idea-plugin#146]
Hello there,

I'm using the plugin on a Mac with the environment variable set in my .zshrc. De-/encryption on the command line with the ansivle-vault binary works using the env variable. 
Sadly the plugin asks me everytime for the password instead of looking it up in the file set in the env variable. I don't get where the problem is. Tried it with a text file contain the cleartext passwords as well as a shell script echoing the password.

**Comment by sadv1r** [comment]
Hi, thanks for using the plugin.

When you using .zshrc, this variable is only visible inside your bash session. You need to set it globally, so it can be visible inside IDEA plugins.

On Mac OS you can do it like this:
`launchctl setenv ANSIBLE_VAULT_PASSWORD_FILE ~/passfile.txt`

**Comment by RickS-C137** [comment]
Yeah, I found that too. This way it isn't reboot safe. For this I've created a launch agent, which is loaded on any boot:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.seb.ansible_vault_password</string>

  <key>ProgramArguments</key>
  <array>
    <string>launchctl</string>
    <string>setenv</string>
    <string>ANSIBLE_VAULT_PASSWORD_FILE</string>
    <string>~/.ansible-vault-password.sh</string>
  </array>

  <key>Nice</key>
  <integer>1</integer>

  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
`
The ansible-vault-password.sh reads the password from my MacOS keychain.
`#!/bin/zsh
security find-generic-password -a $USER -s ansible-vault -w`
