### ISSUE TITLE
Add possibility to change vault password

### ISSUE THREAD

**Issue by sadv1r** [sadv1r/ansible-vault-editor-idea-plugin#18]

**Comment by kcrebound** [comment]
Привет, чтобы не вводить пароль каждый раз можно сделать через пароль в файлике?
`.vault.txt` допустим в gitignore лежит и в ansbile.cfg

```
[defaults]
vault_password_file = .vault.txt
```

**Comment by sadv1r** [comment]
> Привет, чтобы не вводить пароль каждый раз можно сделать через пароль в файлике?
> `.vault.txt` допустим в gitignore лежит и в ansbile.cfg
> 
> ```
> [defaults]
> vault_password_file = .vault.txt
> ```

Привет, в планах есть идея добавлять пароль от файла в стандартное хранилище IDE. Сделал сначала упрощенный вариант, потому как там вставали проблемы вида, как удалить пароль из хранилища, если файлик этого волта был удален (создавать отдельный Tool Window или окно в настройках не хотелось ради такого).
Вариант с простым файлом проще, но появляется опасность запушить случайно, стоит подумать, какой вариант выбрать

**Comment by sadv1r** [comment]
@kcrebound реализовано в [1.2](https://plugins.jetbrains.com/plugin/14278-ansible-vault-editor/update/86186)
