### ISSUE TITLE
Add Support for IntelliJ IDEA 2022.3

### ISSUE THREAD

**Issue by thees** [sadv1r/ansible-vault-editor-idea-plugin#187]
In IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022

the plugin is no longer working. The icon on the side is no longer there.

So something seems to be needed to support the latest version if IntelliJ.

**Comment by mordekasg** [comment]
I`ve just updated my IDE to latest version (IntelliJ IDEA 2022.3 (Ultimate Edition), Build #IU-223.7571.182, built on November 29, 2022) and plugin is working just fine.
There are available all options:

- top menu: Tools -> Encrypt File as Ansible Vault,
- context menu option,
- icon (document sidebar with line numbers).

Are you sure that the file indexing process has finished before you`ve tried to use the plugin?

**Comment by thees** [comment]
Damn you are so right. I am sorry!

Although I doubled checked that the project was loaded, something was not ready yet.
It's working just fine. Closing this ticket.
