### ISSUE TITLE
Wrong line separators: '{\r\n  \"ENABL...' at offset 1

### ISSUE THREAD

**Issue by morovinger** [sadv1r/ansible-vault-editor-idea-plugin#235]
This error exist for quite a while, and coz latly i have to develop on windows i would like to report it
![image](https://github.com/sadv1r/ansible-vault-editor-idea-plugin/assets/16294149/57d3a185-53cd-4cf1-bb8e-f800900ca9bd)

**Comment by sadv1r** [comment]
@morovinger Thank you for submitting! 👍
