### ISSUE TITLE
Add encrypted YAML properties creation support

### ISSUE THREAD

**Issue by sadv1r** [sadv1r/ansible-vault-editor-idea-plugin#46]

**Comment by megadrifter** [comment]
Do you mean this will encrypt/decrypt only one value of chosen property? 
First you can implement working not with all file contents, but with SELECTED text (it may contain spaces from line beginning).

**Comment by megadrifter** [comment]
Sorry, i see it is done in 1.6.
Maybe you should close the issue.

**Comment by sadv1r** [comment]
Hi! Thanks for your attention here)
Currently you can modify !vault property inside yaml file, but you can't create a new one or encrypt some unencrypted property
