### ISSUE TITLE
Add work with multiple vault format version

### ISSUE THREAD

**Issue by aelexor** [sadv1r/ansible-vault-editor-idea-plugin#51]
Hi!

I have a problem with encrypted my vault files because plugin doesn't work with vault format version 1.2 and additional string, for example:

<img width="648" alt="Screenshot 2020-11-02 at 00 56 14" src="https://user-images.githubusercontent.com/32645155/97816431-36888e80-1ca6-11eb-9a0c-1464537ebae7.png">

Please, add able to work with vault format version 1.2 and work with additional strings how example above.

**Comment by sadv1r** [comment]
Mentioned in #38.
I will work on it in the nearest future, thanks!

**Comment by sadv1r** [comment]
Done in #53
