### ISSUE TITLE
How can i specify the vault ID?

### ISSUE THREAD

**Issue by zentavr** [sadv1r/ansible-vault-editor-idea-plugin#84]
We are using several vaults in our repo and a couple of them have different passwords.
Ansible supports providing several vaults IDs and different passwords for them, the same in about Ansibel Tower/AWX.

How can I use the plugin in order to set up the vault witn an ID and password?

[Ansible Vault and several passwords documentation](https://docs.ansible.com/ansible/latest/user_guide/vault.html#passing-multiple-vault-passwords)

**Comment by sadv1r** [comment]
Hi, thanks for your question. Using this plugin you can manually add any vault ID at the end of vault header line, like: `$ANSIBLE_VAULT;1.2;AES256;vault-id-label` and official Ansible tool will understand this. It will detect required password using this ID.

At the same time, this plugin do not need vault id labels to store different passwords for vaults. It stores passwords using full file path in your project.

So you can use different passwords without providing Vault ID labels in this plugin. But you can add label to the vault and plugin will work correctly with it.

**Comment by zentavr** [comment]
@sadv1r thank you for the reply. I wonder what would happen if we decide to change the vault later? Will the plug-in replace the "header"?

**Comment by sadv1r** [comment]
Plugin will use existing version and ID label.
