### ISSUE TITLE
Support ANSIBLE_VAULT_PASSWORD_FILE environment variable

### ISSUE THREAD

**Issue by wheelerlaw** [sadv1r/ansible-vault-editor-idea-plugin#90]
The `ANSIBLE_VAULT_PASSWORD_FILE` environment variable tells Ansible where to locate the password for the vault. It would be nice if this plugin supported that if it was detected, and if the password located in the location that variable pointed to did not work, then the password prompt would pop up. 

More documentation can be found here: https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-vault-password-file

**Comment by wheelerlaw** [comment]
So I gave it a shot. I don't really know how to do IntelliJ Plugin development so I don't know how to test this out, and this is pretty sloppy code since there is a bunch of duplication, but it's a first stab at it. 

The workflow is as follows:

- Check for environment variable. 
  - If null, check for saved password and try that. 
      - If saved variable is null or does not work, prompt for password
  - If not null, try password in environment variable. 
    - If environment variable does not work, check for saved password and try that
      - If saved variable is null or does not work, prompt for password

```kotlin
    override fun actionPerformed(e: AnActionEvent) {
        val document = e.getData(PlatformDataKeys.EDITOR)?.document ?: return
        val vault = FileVault(document)

        val password = System.getenv("ANSIBLE_VAULT_PASSWORD_FILE")
        if (password == null) {
            trySavedPassword(vault)
        } else {
            try {
                VaultEditorDialog(
                    vault.getDecryptedData(password),
                    password.toCharArray(),
                    vault
                ).showAndGet()
            } catch (e: IOException) {
                trySavedPassword(vault)
            }
        }
    }
    
    private fun trySavedPassword(vault: FileVault) {
        val password = getPassword(vault)
        if (password == null) {
            VaultPasswordDialog(vault).showAndGet()
        } else {
            try {
                VaultEditorDialog(
                    vault.getDecryptedData(password),
                    password.toCharArray(),
                    vault
                ).showAndGet()
            } catch (e: IOException) {
                removePassword(vault)
                VaultPasswordDialog(vault).showAndGet()
            }
        }
    }

```

**Comment by sadv1r** [comment]
Hi @wheelerlaw, thanks for the detailed description and link to DEFAULT_VAULT_PASSWORD_FILE.

This is a nice feature, but I have a question: why not use DEFAULT_VAULT_PASSWORD_FILE environment, same as official tool?
